# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exper_cn', models.TextField()),
                ('exper_eng', models.TextField()),
                ('intro_cn', models.TextField()),
                ('intro_eng', models.TextField()),
                ('picture_name', models.CharField(max_length=32)),
            ],
        ),
    ]
