# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0002_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
