# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0003_series_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturepath', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='works',
            name='picturepath',
        ),
        migrations.AddField(
            model_name='picture_path',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelrydisplay.works'),
        ),
    ]
