# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0004_auto_20180602_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
