# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0007_auto_20180605_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='workname',
        ),
    ]
