# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0008_remove_works_workname'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_path',
            name='isBroadcast',
            field=models.BooleanField(default=False),
        ),
    ]
