# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0009_picture_path_isbroadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='intro_eng',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='seriesname_eng',
            field=models.TextField(default=''),
        ),
    ]
