# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0010_auto_20180704_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='picture_name',
            field=models.CharField(max_length=256),
        ),
    ]
