# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelrydisplay', '0011_auto_20180728_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_pic',
            field=models.CharField(default='', max_length=32),
        ),
    ]
